function gradu = singletrack_gradu_f_3o(in1,in2,in3)
%SINGLETRACK_GRADU_F_3O
%    GRADU = SINGLETRACK_GRADU_F_3O(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    31-Oct-2023 09:57:43

gradu = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,11]);
