# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ltv_mpc/gp_data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ltv_mpc.msg

class gp_data(genpy.Message):
  _md5sum = "2757ea2368b9f205bb07f6799989923c"
  _type = "ltv_mpc/gp_data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """gpinput gp_input
gpoutput gp_output
================================================================================
MSG: ltv_mpc/gpinput
float64 v
float64 r
float64 beta
float64 Tf
float64 Tr
float64 Steer
================================================================================
MSG: ltv_mpc/gpoutput
float64 v_error
float64 r_error
float64 beta_error"""
  __slots__ = ['gp_input','gp_output']
  _slot_types = ['ltv_mpc/gpinput','ltv_mpc/gpoutput']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gp_input,gp_output

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gp_data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gp_input is None:
        self.gp_input = ltv_mpc.msg.gpinput()
      if self.gp_output is None:
        self.gp_output = ltv_mpc.msg.gpoutput()
    else:
      self.gp_input = ltv_mpc.msg.gpinput()
      self.gp_output = ltv_mpc.msg.gpoutput()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.gp_input.v, _x.gp_input.r, _x.gp_input.beta, _x.gp_input.Tf, _x.gp_input.Tr, _x.gp_input.Steer, _x.gp_output.v_error, _x.gp_output.r_error, _x.gp_output.beta_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gp_input is None:
        self.gp_input = ltv_mpc.msg.gpinput()
      if self.gp_output is None:
        self.gp_output = ltv_mpc.msg.gpoutput()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.gp_input.v, _x.gp_input.r, _x.gp_input.beta, _x.gp_input.Tf, _x.gp_input.Tr, _x.gp_input.Steer, _x.gp_output.v_error, _x.gp_output.r_error, _x.gp_output.beta_error,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.gp_input.v, _x.gp_input.r, _x.gp_input.beta, _x.gp_input.Tf, _x.gp_input.Tr, _x.gp_input.Steer, _x.gp_output.v_error, _x.gp_output.r_error, _x.gp_output.beta_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gp_input is None:
        self.gp_input = ltv_mpc.msg.gpinput()
      if self.gp_output is None:
        self.gp_output = ltv_mpc.msg.gpoutput()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.gp_input.v, _x.gp_input.r, _x.gp_input.beta, _x.gp_input.Tf, _x.gp_input.Tr, _x.gp_input.Steer, _x.gp_output.v_error, _x.gp_output.r_error, _x.gp_output.beta_error,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
