# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ltv_mpc/gpinput.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class gpinput(genpy.Message):
  _md5sum = "dfd53f116b4d87a2c94142f47b445347"
  _type = "ltv_mpc/gpinput"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 v
float64 r
float64 beta
float64 Tf
float64 Tr
float64 Steer"""
  __slots__ = ['v','r','beta','Tf','Tr','Steer']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       v,r,beta,Tf,Tr,Steer

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gpinput, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.v is None:
        self.v = 0.
      if self.r is None:
        self.r = 0.
      if self.beta is None:
        self.beta = 0.
      if self.Tf is None:
        self.Tf = 0.
      if self.Tr is None:
        self.Tr = 0.
      if self.Steer is None:
        self.Steer = 0.
    else:
      self.v = 0.
      self.r = 0.
      self.beta = 0.
      self.Tf = 0.
      self.Tr = 0.
      self.Steer = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.v, _x.r, _x.beta, _x.Tf, _x.Tr, _x.Steer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.v, _x.r, _x.beta, _x.Tf, _x.Tr, _x.Steer,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.v, _x.r, _x.beta, _x.Tf, _x.Tr, _x.Steer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.v, _x.r, _x.beta, _x.Tf, _x.Tr, _x.Steer,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
