# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ltv_mpc/sample.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sample(genpy.Message):
  _md5sum = "70403b52d11f6e3bff793167877b89ed"
  _type = "ltv_mpc/sample"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 yaw
float64 v
float64 r
float64 beta
float64 tf
float64 tr
float64 steer
float64 s
float64 time
float64 iter
float64 cost"""
  __slots__ = ['x','y','yaw','v','r','beta','tf','tr','steer','s','time','iter','cost']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,yaw,v,r,beta,tf,tr,steer,s,time,iter,cost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sample, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.v is None:
        self.v = 0.
      if self.r is None:
        self.r = 0.
      if self.beta is None:
        self.beta = 0.
      if self.tf is None:
        self.tf = 0.
      if self.tr is None:
        self.tr = 0.
      if self.steer is None:
        self.steer = 0.
      if self.s is None:
        self.s = 0.
      if self.time is None:
        self.time = 0.
      if self.iter is None:
        self.iter = 0.
      if self.cost is None:
        self.cost = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.yaw = 0.
      self.v = 0.
      self.r = 0.
      self.beta = 0.
      self.tf = 0.
      self.tr = 0.
      self.steer = 0.
      self.s = 0.
      self.time = 0.
      self.iter = 0.
      self.cost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
