# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ltv_mpc/sample_lst.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ltv_mpc.msg

class sample_lst(genpy.Message):
  _md5sum = "4b7f364dc273676e8884e28e28f4d153"
  _type = "ltv_mpc/sample_lst"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """sample[] sample_list
================================================================================
MSG: ltv_mpc/sample
float64 x
float64 y
float64 yaw
float64 v
float64 r
float64 beta
float64 tf
float64 tr
float64 steer
float64 s
float64 time
float64 iter
float64 cost"""
  __slots__ = ['sample_list']
  _slot_types = ['ltv_mpc/sample[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sample_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sample_lst, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sample_list is None:
        self.sample_list = []
    else:
      self.sample_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.sample_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.sample_list:
        _x = val1
        buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sample_list is None:
        self.sample_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sample_list = []
      for i in range(0, length):
        val1 = ltv_mpc.msg.sample()
        _x = val1
        start = end
        end += 104
        (_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost,) = _get_struct_13d().unpack(str[start:end])
        self.sample_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.sample_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.sample_list:
        _x = val1
        buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sample_list is None:
        self.sample_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sample_list = []
      for i in range(0, length):
        val1 = ltv_mpc.msg.sample()
        _x = val1
        start = end
        end += 104
        (_x.x, _x.y, _x.yaw, _x.v, _x.r, _x.beta, _x.tf, _x.tr, _x.steer, _x.s, _x.time, _x.iter, _x.cost,) = _get_struct_13d().unpack(str[start:end])
        self.sample_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
