// Generated by gencpp from file ltv_mpc/gp_data.msg
// DO NOT EDIT!


#ifndef LTV_MPC_MESSAGE_GP_DATA_H
#define LTV_MPC_MESSAGE_GP_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ltv_mpc/gpinput.h>
#include <ltv_mpc/gpoutput.h>

namespace ltv_mpc
{
template <class ContainerAllocator>
struct gp_data_
{
  typedef gp_data_<ContainerAllocator> Type;

  gp_data_()
    : gp_input()
    , gp_output()  {
    }
  gp_data_(const ContainerAllocator& _alloc)
    : gp_input(_alloc)
    , gp_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ltv_mpc::gpinput_<ContainerAllocator>  _gp_input_type;
  _gp_input_type gp_input;

   typedef  ::ltv_mpc::gpoutput_<ContainerAllocator>  _gp_output_type;
  _gp_output_type gp_output;





  typedef boost::shared_ptr< ::ltv_mpc::gp_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltv_mpc::gp_data_<ContainerAllocator> const> ConstPtr;

}; // struct gp_data_

typedef ::ltv_mpc::gp_data_<std::allocator<void> > gp_data;

typedef boost::shared_ptr< ::ltv_mpc::gp_data > gp_dataPtr;
typedef boost::shared_ptr< ::ltv_mpc::gp_data const> gp_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltv_mpc::gp_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltv_mpc::gp_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltv_mpc::gp_data_<ContainerAllocator1> & lhs, const ::ltv_mpc::gp_data_<ContainerAllocator2> & rhs)
{
  return lhs.gp_input == rhs.gp_input &&
    lhs.gp_output == rhs.gp_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltv_mpc::gp_data_<ContainerAllocator1> & lhs, const ::ltv_mpc::gp_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltv_mpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gp_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gp_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gp_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gp_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gp_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gp_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltv_mpc::gp_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2757ea2368b9f205bb07f6799989923c";
  }

  static const char* value(const ::ltv_mpc::gp_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2757ea2368b9f205ULL;
  static const uint64_t static_value2 = 0xbb07f6799989923cULL;
};

template<class ContainerAllocator>
struct DataType< ::ltv_mpc::gp_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltv_mpc/gp_data";
  }

  static const char* value(const ::ltv_mpc::gp_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltv_mpc::gp_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpinput gp_input\n"
"gpoutput gp_output\n"
"================================================================================\n"
"MSG: ltv_mpc/gpinput\n"
"float64 v\n"
"float64 r\n"
"float64 beta\n"
"float64 Tf\n"
"float64 Tr\n"
"float64 Steer\n"
"================================================================================\n"
"MSG: ltv_mpc/gpoutput\n"
"float64 v_error\n"
"float64 r_error\n"
"float64 beta_error\n"
;
  }

  static const char* value(const ::ltv_mpc::gp_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltv_mpc::gp_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gp_input);
      stream.next(m.gp_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gp_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltv_mpc::gp_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltv_mpc::gp_data_<ContainerAllocator>& v)
  {
    s << indent << "gp_input: ";
    s << std::endl;
    Printer< ::ltv_mpc::gpinput_<ContainerAllocator> >::stream(s, indent + "  ", v.gp_input);
    s << indent << "gp_output: ";
    s << std::endl;
    Printer< ::ltv_mpc::gpoutput_<ContainerAllocator> >::stream(s, indent + "  ", v.gp_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTV_MPC_MESSAGE_GP_DATA_H
