// Generated by gencpp from file ltv_mpc/gp_srv.msg
// DO NOT EDIT!


#ifndef LTV_MPC_MESSAGE_GP_SRV_H
#define LTV_MPC_MESSAGE_GP_SRV_H

#include <ros/service_traits.h>


#include <ltv_mpc/gp_srvRequest.h>
#include <ltv_mpc/gp_srvResponse.h>


namespace ltv_mpc
{

struct gp_srv
{

typedef gp_srvRequest Request;
typedef gp_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gp_srv
} // namespace ltv_mpc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ltv_mpc::gp_srv > {
  static const char* value()
  {
    return "44a6e9c0a8d485a5d5e43661bad4e2ba";
  }

  static const char* value(const ::ltv_mpc::gp_srv&) { return value(); }
};

template<>
struct DataType< ::ltv_mpc::gp_srv > {
  static const char* value()
  {
    return "ltv_mpc/gp_srv";
  }

  static const char* value(const ::ltv_mpc::gp_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ltv_mpc::gp_srvRequest> should match
// service_traits::MD5Sum< ::ltv_mpc::gp_srv >
template<>
struct MD5Sum< ::ltv_mpc::gp_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ltv_mpc::gp_srv >::value();
  }
  static const char* value(const ::ltv_mpc::gp_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltv_mpc::gp_srvRequest> should match
// service_traits::DataType< ::ltv_mpc::gp_srv >
template<>
struct DataType< ::ltv_mpc::gp_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ltv_mpc::gp_srv >::value();
  }
  static const char* value(const ::ltv_mpc::gp_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ltv_mpc::gp_srvResponse> should match
// service_traits::MD5Sum< ::ltv_mpc::gp_srv >
template<>
struct MD5Sum< ::ltv_mpc::gp_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ltv_mpc::gp_srv >::value();
  }
  static const char* value(const ::ltv_mpc::gp_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ltv_mpc::gp_srvResponse> should match
// service_traits::DataType< ::ltv_mpc::gp_srv >
template<>
struct DataType< ::ltv_mpc::gp_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ltv_mpc::gp_srv >::value();
  }
  static const char* value(const ::ltv_mpc::gp_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LTV_MPC_MESSAGE_GP_SRV_H
