// Generated by gencpp from file ltv_mpc/gp_srvResponse.msg
// DO NOT EDIT!


#ifndef LTV_MPC_MESSAGE_GP_SRVRESPONSE_H
#define LTV_MPC_MESSAGE_GP_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ltv_mpc/gpoutput.h>

namespace ltv_mpc
{
template <class ContainerAllocator>
struct gp_srvResponse_
{
  typedef gp_srvResponse_<ContainerAllocator> Type;

  gp_srvResponse_()
    : gp_output_now()  {
    }
  gp_srvResponse_(const ContainerAllocator& _alloc)
    : gp_output_now(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ltv_mpc::gpoutput_<ContainerAllocator>  _gp_output_now_type;
  _gp_output_now_type gp_output_now;





  typedef boost::shared_ptr< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gp_srvResponse_

typedef ::ltv_mpc::gp_srvResponse_<std::allocator<void> > gp_srvResponse;

typedef boost::shared_ptr< ::ltv_mpc::gp_srvResponse > gp_srvResponsePtr;
typedef boost::shared_ptr< ::ltv_mpc::gp_srvResponse const> gp_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltv_mpc::gp_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltv_mpc::gp_srvResponse_<ContainerAllocator1> & lhs, const ::ltv_mpc::gp_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.gp_output_now == rhs.gp_output_now;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltv_mpc::gp_srvResponse_<ContainerAllocator1> & lhs, const ::ltv_mpc::gp_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltv_mpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b3f30157fff2a48622f40da7c543041";
  }

  static const char* value(const ::ltv_mpc::gp_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b3f30157fff2a48ULL;
  static const uint64_t static_value2 = 0x622f40da7c543041ULL;
};

template<class ContainerAllocator>
struct DataType< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltv_mpc/gp_srvResponse";
  }

  static const char* value(const ::ltv_mpc::gp_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpoutput gp_output_now\n"
"\n"
"================================================================================\n"
"MSG: ltv_mpc/gpoutput\n"
"float64 v_error\n"
"float64 r_error\n"
"float64 beta_error\n"
;
  }

  static const char* value(const ::ltv_mpc::gp_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gp_output_now);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gp_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltv_mpc::gp_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltv_mpc::gp_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "gp_output_now: ";
    s << std::endl;
    Printer< ::ltv_mpc::gpoutput_<ContainerAllocator> >::stream(s, indent + "  ", v.gp_output_now);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTV_MPC_MESSAGE_GP_SRVRESPONSE_H
