// Generated by gencpp from file ltv_mpc/gpoutput.msg
// DO NOT EDIT!


#ifndef LTV_MPC_MESSAGE_GPOUTPUT_H
#define LTV_MPC_MESSAGE_GPOUTPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ltv_mpc
{
template <class ContainerAllocator>
struct gpoutput_
{
  typedef gpoutput_<ContainerAllocator> Type;

  gpoutput_()
    : v_error(0.0)
    , r_error(0.0)
    , beta_error(0.0)  {
    }
  gpoutput_(const ContainerAllocator& _alloc)
    : v_error(0.0)
    , r_error(0.0)
    , beta_error(0.0)  {
  (void)_alloc;
    }



   typedef double _v_error_type;
  _v_error_type v_error;

   typedef double _r_error_type;
  _r_error_type r_error;

   typedef double _beta_error_type;
  _beta_error_type beta_error;





  typedef boost::shared_ptr< ::ltv_mpc::gpoutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltv_mpc::gpoutput_<ContainerAllocator> const> ConstPtr;

}; // struct gpoutput_

typedef ::ltv_mpc::gpoutput_<std::allocator<void> > gpoutput;

typedef boost::shared_ptr< ::ltv_mpc::gpoutput > gpoutputPtr;
typedef boost::shared_ptr< ::ltv_mpc::gpoutput const> gpoutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ltv_mpc::gpoutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ltv_mpc::gpoutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ltv_mpc::gpoutput_<ContainerAllocator1> & lhs, const ::ltv_mpc::gpoutput_<ContainerAllocator2> & rhs)
{
  return lhs.v_error == rhs.v_error &&
    lhs.r_error == rhs.r_error &&
    lhs.beta_error == rhs.beta_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ltv_mpc::gpoutput_<ContainerAllocator1> & lhs, const ::ltv_mpc::gpoutput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ltv_mpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gpoutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ltv_mpc::gpoutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gpoutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ltv_mpc::gpoutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gpoutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ltv_mpc::gpoutput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ltv_mpc::gpoutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "529d1c55d988fb7bb8a7cea9ad6453f5";
  }

  static const char* value(const ::ltv_mpc::gpoutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x529d1c55d988fb7bULL;
  static const uint64_t static_value2 = 0xb8a7cea9ad6453f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ltv_mpc::gpoutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ltv_mpc/gpoutput";
  }

  static const char* value(const ::ltv_mpc::gpoutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ltv_mpc::gpoutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 v_error\n"
"float64 r_error\n"
"float64 beta_error\n"
;
  }

  static const char* value(const ::ltv_mpc::gpoutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ltv_mpc::gpoutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_error);
      stream.next(m.r_error);
      stream.next(m.beta_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gpoutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltv_mpc::gpoutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ltv_mpc::gpoutput_<ContainerAllocator>& v)
  {
    s << indent << "v_error: ";
    Printer<double>::stream(s, indent + "  ", v.v_error);
    s << indent << "r_error: ";
    Printer<double>::stream(s, indent + "  ", v.r_error);
    s << indent << "beta_error: ";
    Printer<double>::stream(s, indent + "  ", v.beta_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LTV_MPC_MESSAGE_GPOUTPUT_H
