function gradx = singletrack_gradx_f_lear(in1,dert,in3)
%SINGLETRACK_GRADX_F_LEAR
%    GRADX = SINGLETRACK_GRADX_F_LEAR(IN1,DERT,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    05-Jul-2022 18:27:06

C_f = in3(10,:);
C_r = in3(11,:);
I_z = in3(4,:);
L_f = in3(2,:);
L_r = in3(3,:);
e_d = in1(4,:);
e_psi = in1(3,:);
kr = in3(6,:);
m = in3(5,:);
psi_dot = in1(1,:);
v_x = in3(12,:);
v_y = in1(2,:);
t2 = cos(dert);
t3 = cos(e_psi);
t4 = sin(e_psi);
t5 = L_f.*psi_dot;
t6 = L_r.*psi_dot;
t7 = e_d.*kr;
t8 = 1.0./I_z;
t9 = 1.0./m;
t10 = 1.0./v_x;
t11 = t10.^2;
t12 = -t6;
t13 = t5+v_y;
t14 = t7-1.0;
t17 = (t6-v_y).^2;
t15 = t13.^2;
t16 = t12+v_y;
t18 = 1.0./t14;
t20 = t11.*t17;
t19 = t11.*t15;
t22 = t20+1.0;
t21 = t19+1.0;
t24 = 1.0./t22;
t23 = 1.0./t21;
t25 = C_r.*L_r.*t10.*t24;
t26 = C_f.*L_f.*t2.*t10.*t23;
t27 = -t26;
t28 = t25+t27;
gradx = reshape([-t8.*(L_f.*t26+L_r.*t25),t8.*t28,0.0,0.0,-v_x+t9.*t28,-t9.*(C_r.*t10.*t24+C_f.*t2.*t10.*t23),0.0,0.0,1.0,-kr.*t4.*t18,-kr.*t18.*(t4.*v_x+t3.*v_y),-kr.^2.*t18.^2.*(t3.*v_x-t4.*v_y),0.0,1.0,v_x,0.0],[4,4]);
