function gradu = singletrack_gradu_f_lear(in1,dert,in3)
%SINGLETRACK_GRADU_F_LEAR
%    GRADU = SINGLETRACK_GRADU_F_LEAR(IN1,DERT,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    05-Jul-2022 18:27:06

C_f = in3(10,:);
I_z = in3(4,:);
L_f = in3(2,:);
m = in3(5,:);
psi_dot = in1(1,:);
v_x = in3(12,:);
v_y = in1(2,:);
t2 = cos(dert);
t3 = sin(dert);
t4 = L_f.*psi_dot;
t5 = 1.0./v_x;
t6 = t4+v_y;
t7 = t5.*t6;
t8 = atan(t7);
t9 = -t8;
t10 = dert+t9;
gradu = [(C_f.*L_f.*t2-C_f.*L_f.*t3.*t10)./I_z,(C_f.*t2-C_f.*t3.*t10)./m,0.0,0.0];
