function gradu = singletrack_gradu_f_3o_xy(in1,in2,in3)
%SINGLETRACK_GRADU_F_3O_XY
%    GRADU = SINGLETRACK_GRADU_F_3O_XY(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Nov-2023 07:10:22

gradu = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,11]);
